### PR TITLE
Require Consumer Image Styles on CI

### PR DESCRIPTION
**Pull request by phenaproxima**
Until we add this to our container image, let's add Consumer Image Styles to the Drupal backend so we can work on that.

### CODE REVIEW

**Comment by lauriii** [comment]
Alright, it seems like CI is passing for this. Should we merge this to #102? There are additional steps needed because we will have to also enable image styles for the consumer that we use for testing, so that we can actually test this.

**Comment by phenaproxima** [comment]
I'd suggest we add the module to our actual container build and enable it, along with any needed configuration changes in `init-env.php`.

**Comment by phenaproxima** [comment]
Judging by the failure message from Cypress: https://github.com/acquia/next-acms/runs/7899102781?check_suite_focus=true#step:16:160

Is it possible that the test is too fragile here? Maybe it's expecting the _first_ found `h2` to be "Boston Head Office", which is certainly not something we can guarantee, since the order is not deterministic.

**Comment by phenaproxima** [comment]
Closing this because Consumer Image Styles will be added to Acquia CMS in https://backlog.acquia.com/browse/ACMS-1356. When it's released, all we'll need to do is rebuild our container image.

**Pull request closed without merging**
