### PR TITLE
Add scripts and documentation to rebuild the Acquia CMS container image

### PR DESCRIPTION
**Pull request by phenaproxima**
In theory, `build.sh` should rebuild the container image we use and tag it `phenaproxima/acquia_cms:headless`. If you have push access (currently that's just me and @lauriii), you can push the rebuilt image to Docker Hub, at which point it will start being used in our CI jobs.

You need two things before you can the script: a container runtime (I'm using Colima) and the Docker Engine (i.e., the `docker` command line utility).

### CODE REVIEW

**Comment by phenaproxima** [comment]
You can test this locally by fulfilling the prerequisites (a container runtime and the Docker Engine) and running `build.sh` without any arguments. If all goes well, `docker image ls` should reveal that you have an image tagged `phenaproxima/acquia_cms:headless`.

**Comment by lauriii** [comment]
I'm wondering if we could automate this so that this would be run on Github Actions few times a week?

**Comment by phenaproxima** [comment]
Yeah, I think we should. Probably not in this PR, but I do think it'd be wise to try and keep our ACMS image up to date.

**Comment by phenaproxima** [comment]
At what stage in the build was this?

**Comment by lauriii** [comment]
This was the command it was running:

```
executor failed running [/bin/sh -c DRUSH_COMMAND_SITE_INSTALL_OPTIONS_DB_URL=mysql://drupal:drupal@host.docker.internal:3306/drupal DRUSH_COMMAND_SITE_INSTALL_OPTIONS_ACCOUNT_PASS=admin ./vendor/bin/acms acms:install --no-interaction acquia_cms_headless]: exit code: 1
4385ca672cd433c8d29e85ae25049727631ad78d8459455d56978e5623265a1a
```

**Review by lauriii — APPROVED** [review]

**Review by lauriii — APPROVED** [review]

**Pull request merged**
