### PR TITLE
Adding context to getMenus() for locale support

### PR DESCRIPTION
**Pull request by joshirohit100**

### CODE REVIEW

**Review by harumijang — CHANGES_REQUESTED** [review]
> Steps -
> 
> * Setup multilingual drupal site
> * Setup nextjs app with 2 locales
> * Update / add menu in drupal for different languages
> * Notice the next app on FE - Menus are showing in english only and not in the language / locale of the app
> 
> This is happening because - `drupal.getMenu()` of the next-drupal, expects locale to be passed as an argument and not relies or uses context like other methods (ex - getResourceCollectionFromContext())
> 
> So - `getMenus()` of `lib/get-menus.ts` - we need to pass context as an argument from caller and to this getMenu() and then need to pass the locale

@joshirohit100 @lauriii  I tried to test this and I added Spanish as another language and updated my menu links to have spanish translations and also added a locale on http://acms-demo.test/en/admin/config/regional/settings but am still getting undefined values.

`context { locales: undefined, locale: undefined, defaultLocale: undefined }
`

How do you setup the nextjs app with 2 locales? Does that require a config file in the nextjs app or is that configurable on ACMS?

**Comment by joshirohit100** [comment]
@harumijang you also need to add locales in nextc onfig. Reference - https://nextjs.org/docs/advanced-features/i18n-routing#getting-started

**Comment by joshirohit100** [comment]
rebased and fixed the eslint issue

**Comment by harumijang** [comment]
@joshirohit100 Would you mind outlining the steps to 
- Setup multilingual drupal site
- Update / add menu in drupal for different languages

on ACMS? 

Because I 
- added Spanish as another language on `/admin/config/regional/language`
- added Spanish translations to each of the main menu items on  `/admin/structure/menu/manage/main` 
- set the language for Custom menu links to Spanish on `/admin/config/regional/content-language`
  
but it's still not translating on my nextjs site so I'm wondering if I'm missing something else on the ACMS side.

I did get context to set the locales correctly after adding them to the nextconfig.

**Comment by joshirohit100** [comment]
**Steps** -

- Setup the headless ACMS starter kit using the command `./vendor/bin/acms acms:install` with the demo content
- Visit `/admin/config/regional/language` to add a new language say Snanish (langcode=es)
- Configure the locales in nextjs as per https://nextjs.org/docs/advanced-features/i18n-routing#getting-started
- Go to `/admin/content` and edit any existing article (or add new article) and add content for both EN and ES
- Visit the site NextJS site `/es/articles` and notice it will show you the spanish version of articles if available
- For menu => Visit main menu `/admin/structure/menu/manage/main`
- Edit the `Articles` main menu link and add the spanish translation for the link
- Now verify on the nextjs site by visiting `/es` locale on site

**Comment by harumijang** [comment]
@joshirohit100 Thank you! Got it to work. I didn't add any translation to an article before which I guess is what I was missing.

**Comment by harumijang** [comment]
Works as expected 👍

Head:
Screen Shot 2022-09-19 at 12 03 12 PM


This PR:
Screen Shot 2022-09-19 at 12 03 40 PM


Tested with next.config.js
```
module.exports = {
  images: {
    domains: [process.env.NEXT_IMAGE_DOMAIN ?? ''],
  },
  i18n: {
    locales: ['es', 'en'],
    defaultLocale: 'en',
  },
};
``` 

Tested in dev mode because there is a build error complaining about /es/ pages that don't exist because I only added translations for one article.

**Comment by joshirohit100** [comment]
Yes! build error is there (for me as well) and seems its because of https://www.drupal.org/project/decoupled_router/issues/3111456

**Review by harumijang — APPROVED** [review]

**Review by lauriii — APPROVED** [review]
Thank you @joshirohit100! This looks great 💯

**Pull request merged**
